"""
QuantumShield-IoT
Real-Time AI Multi-Class Threat Detector
"""

import os
import sys
import joblib
import pandas as pd

# -----------------------------------------
# DATABASE IMPORT
# -----------------------------------------

sys.path.append(
    os.path.abspath(
        os.path.join(
            os.path.dirname(__file__),
            ".."
        )
    )
)

from database import (
    SessionLocal,
    ThreatLog
)

# -----------------------------------------
# LOAD MODEL & MAPS
# -----------------------------------------

MODEL_PATH = os.path.join(
    os.path.dirname(__file__),
    "threat_model.pkl"
)

model = joblib.load(MODEL_PATH)
print("Multi-Class Threat Detection Model Loaded")

THREAT_MAP = {
    0: "Normal",
    1: "DDoS",
    2: "Cryptojacking",
    3: "Thermal Tampering",
    4: "Reconnaissance"
}

# -----------------------------------------
# DATABASE
# -----------------------------------------

db = SessionLocal()

# -----------------------------------------
# DETECT THREAT
# -----------------------------------------

def detect_threat(payload):
    try:
        temperature = payload.get("temperature", 0)
        humidity = payload.get("humidity", 0)
        cpu_usage = payload.get("cpu_usage", 0)
        memory_usage = payload.get("memory_usage", 0)
        requests_per_minute = payload.get("requests_per_minute", 20)
        device_id = payload.get("device_id", "unknown")

        features = pd.DataFrame(
            [[
                temperature,
                humidity,
                cpu_usage,
                memory_usage,
                requests_per_minute
            ]],
            columns=[
                "temperature",
                "humidity",
                "cpu_usage",
                "memory_usage",
                "requests_per_minute"
            ]
        )

        prediction = model.predict(features)[0]
        probability = model.predict_proba(features)[0]
        confidence = float(max(probability))

        # Get ground truth from simulator payload
        ground_truth = "Normal"
        if payload.get("attack"):
            ground_truth = payload.get("attack_type", "Normal")
            # Map simulator "Port Scanning" to AI "Reconnaissance"
            if ground_truth == "Port Scanning":
                ground_truth = "Reconnaissance"

        # Determine predicted threat type using AI classification result
        predicted_type = THREAT_MAP.get(prediction, "Normal")

        # Log to DB if either AI predicts an anomaly, OR there is a ground truth anomaly (to capture False Negatives)
        if prediction != 0 or ground_truth != "Normal":
            # Handle severity logic
            severity = "LOW"
            if prediction != 0:
                if confidence > 0.95:
                    severity = "HIGH"
                elif confidence > 0.80:
                    severity = "MEDIUM"

            threat = ThreatLog(
                device_id=device_id,
                threat_type=predicted_type,            # Backward compatible representation
                ground_truth_type=ground_truth,        # Ground truth generated by simulator
                predicted_type=predicted_type,          # AI classification prediction
                confidence=confidence,
                severity=severity,
                temperature=temperature,
                humidity=humidity,
                cpu_usage=cpu_usage,
                memory_usage=memory_usage,
                requests_per_minute=requests_per_minute,
                blocked=(severity == "HIGH")
            )

            db.add(threat)
            db.commit()

            if prediction != 0:
                print(f"Threat Detected [{device_id}] Class={predicted_type} (Conf={confidence*100:.1f}%) | Ground Truth={ground_truth}")
            else:
                print(f"False Negative Detected [{device_id}] Predicted=Normal | Ground Truth={ground_truth}")

        if prediction == 0:
            return {
                "device_id": device_id,
                "threat": False,
                "confidence": confidence,
                "threat_type": "Normal"
            }

        return {
            "device_id": device_id,
            "threat": True,
            "confidence": confidence,
            "severity": severity,
            "threat_type": predicted_type
        }

    except Exception as e:
        print(f"Detection Error: {e}")
        return {
            "error": str(e)
        }