"""add_indexes

Revision ID: 8465fc2cfe66
Revises: f6d76828be4d
Create Date: 2026-08-10 18:49:37.497332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8465fc2cfe66'
down_revision: Union[str, Sequence[str], None] = 'f6d76828be4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_devices_last_seen'), 'devices', ['last_seen'], unique=False)
    op.create_index(op.f('ix_threat_logs_device_id'), 'threat_logs', ['device_id'], unique=False)
    op.create_index(op.f('ix_threat_logs_predicted_type'), 'threat_logs', ['predicted_type'], unique=False)
    op.create_index(op.f('ix_threat_logs_severity'), 'threat_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_threat_logs_timestamp'), 'threat_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_logs_timestamp'), table_name='threat_logs')
    op.drop_index(op.f('ix_threat_logs_severity'), table_name='threat_logs')
    op.drop_index(op.f('ix_threat_logs_predicted_type'), table_name='threat_logs')
    op.drop_index(op.f('ix_threat_logs_device_id'), table_name='threat_logs')
    op.drop_index(op.f('ix_devices_last_seen'), table_name='devices')
    # ### end Alembic commands ###
